#!/bin/bash

echo "Name of the file? (without file extension)"

read name
cd srcs

#cat $name.c			>> .$name.c.save 
echo "/*******************************************************************" >> $name.c
echo "$name source code"	>> $name.c
ls -l | grep $name | tail +14c	>> $name.c
echo "*******************************************************************/" >> $name.c
echo ""				>> $name.c
echo '#include "header.h"'	>> $name.c
echo ""				>> $name.c
echo "int	ft_$name(void)"	>> $name.c
echo "{"			>> $name.c
echo "	/* Your Code */"	>> $name.c
echo "	return (0);"		>> $name.c
echo "}"			>> $name.c

echo "Succesfully created $name.c"
